### ISSUE TITLE
Generate new google-services.json

### ISSUE THREAD

**Issue by gpbonillas** [theVatsal3802/attendance-management-system-teachers#1]
I generated two different new files to setting google firebase services in the apps (for teachers and students), but I have a problem when validate check attendance. I can't find the collections for teachers, because the database firestore are differents.

How can I setup it for the two projects?

Thanks, for your help.

**Comment by theVatsal3802** [comment]
Hello @gpbonillas 

Well, the firestore collection names are different. Please tell me a suitable time when we can connect on google meet so that I can help you out for the same.

**Comment by gpbonillas** [comment]
Thank you!

My email is: gpbonillas@gmail.com
Tomorrow, 11:00 am GMT-5, could you?

**Comment by theVatsal3802** [comment]
Okay, no problem 
We can connect at the above time 
Please join the following link:
https://meet.google.com/wsc-dhcj-cvn/
